/*
* @par Copyright (C): 2010-2019, Shenzhen Yahboom Tech
* @file         humiture monitoring 
* @author       Jessica
* @version      V1.0
* @date         2019.8.21
* @brief        humiture monitoring 
* @details
* @par History  
*
*/
#include "dht11.h"
#define DHT11PIN 2
dht11 DHT11;
int buzzerpin = 13;
int motorpin = 6;
int warn = 0;
float sinVal;
int toneVal;

/*
* Function       setup
* @author        Jessica
* @date          2019.8.21
* @brief         humiture monitoring 
* @param[in]     void
* @retval        void
* @par History   no
*/
void setup() {
  pinMode(DHT11PIN, OUTPUT);
  pinMode(buzzerpin, OUTPUT);         
  pinMode(motorpin, OUTPUT);
  Serial.begin(9600);
}

/*
* Function       buzWarning
* @author        Jessica
* @date          2019.8.21
* @brief         buzzer alarm
* @param[in]     void
* @retval        void
* @par History   no
*/
void buzWarning()
{
	warn = 1;
//    for (int i = 200; i <= 800; i++) 
//    {
//        tone(buzzerpin, i);           
//        delay(5);                     
//    }
	for(int x=0; x<180; x++)
	{
	sinVal = (sin(x*(3.1412/180))); //Convert sin function angle to radian
	toneVal = 2000+(int(sinVal*1000));//Frequency of sound generated by sin function value
	tone(buzzerpin, x);           //Output frequency at port 13
	delay(2);                     //This frequency is maintained for 2 milliseconds
	}
}

/*
* Function       stopWarning
* @author        Jessica
* @date          2019.8.21
* @brief         stop alarm
* @param[in]     void
* @retval        void
* @par History   no
*/
void stopWarning()
{
    warn = 0;
    noTone(buzzerpin);
}

/*
* Function       loop
* @author        Jessica
* @date          2019.8.21
* @brief         main
* @param[in]     void
* @param[out]    void
* @retval        void
* @par History   no
*/
void loop() {
  int chk = DHT11.read(DHT11PIN);
  Serial.print("Tep: ");
  Serial.print((float)DHT11.temperature, 2);
  Serial.println("C");
  Serial.print("Hum: ");
  Serial.print((float)DHT11.humidity, 2);
  Serial.println("%");
  Serial.println();
  if((float)DHT11.temperature >= 29)
  {
    analogWrite(motorpin, 35);//wind speed range: 30~50
  }
  else 
  {
    analogWrite(motorpin, 0);
  }
//  if((float)DHT11.humidity > 70 && warn == 0)
//  {
//    buzWarning();
//  }
//  else if(warn == 1)
//  {
//    stopWarning();
//  }
  delay(1000);
}
